### ISSUE TITLE
Deploy marketplace on ec2

### ISSUE THREAD

**Issue by kulpreet** [ChluNetwork/chlu-marketplace-js#8]

**Comment by fazo96** [comment]
@kulpreet I configured and started the marketplace on EC2, but to work it needs:

- `demomarketplace.chlu.io` needs to point to the EC2 Server
- port `5000` needs to be open on `demomarketplace.chlu.io`

I set up a vendor with ID `QmX4dkij1K9xVEwzxayrSFiBtZ92Ha52og3QxUgSLvf6B1`

After these are OK I'll make a demo build configured to use this marketplace and vendor

EDIT: now hosted at `replicator.chlu.io/marketplace`
